FROM msaraiva/elixir-dev
MAINTAINER You

# Important!  Update this no-op ENV to refresh image
ENV REFRESHED_AT 2016-05-02
ENV HOME /root

# Upgrade all packages and install needed packages
RUN apk --update upgrade && \
  apk add docker erlang-xmerl make && \
  rm -rf /var/cache/apk/*

COPY . /build

ARG APP
ENV MIX_ENV prod

WORKDIR /build

RUN mix deps.get --only prod
RUN mix compile 
RUN echo y | mix release.clean --implode
RUN mix release

WORKDIR /build

CMD ["/bin/sh"]